import React from "react"
import Head from "next/head"

import PageTitle from "@/components/PageTitle"
import PageOverlay from "@/components/PageOverlay"

export default function Metrics() {
  return (
    <>
      <Head>
        <title>Metrics | Nanocl Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.webp" />
      </Head>
      <main id="nano-main">
        <PageOverlay>
          <PageTitle>Metrics</PageTitle>
          <p>Incomming..</p>
        </PageOverlay>
      </main>
    </>
  )
}
