import React from "react"
import Head from "next/head"

export type MetaHeaderProps = {
  title: string
}

const MetaHeader = (props: MetaHeaderProps) => {
  return (
    <Head>
      <title>{props.title || ""} | Nanocl Console</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.webp" />
    </Head>
  )
}

export default MetaHeader
